# This is a basic workflow to help you get started with Actions

name: test docs PR 34253

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Set the value in pwsh
        id: step_one
        run: |
          $EOF = (New-Guid).Guid
          "JSON_RESPONSE<<$EOF" >> $env:GITHUB_ENV
          (Invoke-WebRequest -Uri "https://jsonplaceholder.typicode.com/todos/1").Content >> $env:GITHUB_ENV
          "$EOF" >> $env:GITHUB_ENV
        shell: pwsh
      - name: check env
        run: |
          echo $JSON_RESPONSE
  test-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - name: Set the value in pwsh
        id: step_one
        run: |
          $EOF = (New-Guid).Guid
          "JSON_RESPONSE<<$EOF" >> $env:GITHUB_ENV
          (Invoke-WebRequest -Uri "https://jsonplaceholder.typicode.com/todos/1").Content >> $env:GITHUB_ENV
          "$EOF" >> $env:GITHUB_ENV
        shell: pwsh
      - name: check env
        run: |
          echo $JSON_RESPONSE
